# Generated by Django 5.2.8 on 2025-11-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
