# Generated by Django 5.2.8 on 2025-11-29 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_auto_20251129_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('merch_type', models.CharField(choices=[('T_SHIRT', 'Футболка'), ('STICKER', 'Стикер'), ('HOODIE', 'Толстовка'), ('CAP', 'Кепка'), ('BAG', 'Сумка'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип мерча')),
                ('points_cost', models.IntegerField(verbose_name='Стоимость в баллах')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мерч',
                'verbose_name_plural': 'Мерч',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('points_spent', models.IntegerField(verbose_name='Потрачено баллов')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает обработки'), ('PROCESSING', 'В обработке'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mini.merchandise', verbose_name='Мерч')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merch_orders', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Заказ мерча',
                'verbose_name_plural': 'Заказы мерча',
                'ordering': ['-created_at'],
            },
        ),
    ]
